### ISSUE TITLE
ValidationService doesn't handle multiple constrains for an input

### ISSUE THREAD

**Issue by adrianasbircea** [oxygenxml-incubator/oxygen-account#35]
In issue-ul #27 s-a adaugat un serviciu de validare pentru input-urile de pe REST API. Momentan acesta trateaza doar prima eroare de validare returnata de validator, insa este posibil ca pe un input validatorul sa returneze mai multe erori. Service-ul nostru de validare trebuie sa intoarca catre client toate aceste probleme, nu doar pe prima.

**Comment by matrex32** [comment]
Am configurat serverul sa ne trimita pe /login cand incercam sa accesam /profile
