### ISSUE TITLE
Configure current Git Action to include the frontend module

### ISSUE THREAD

**Issue by adrianasbircea** [oxygenxml-incubator/oxygen-account#36]
Git action-ul curent trebuie configurat astfel incat sa creeze bundle-ul de js si sa ruleze testele de pe frontend. Daca exista cel putin un test de frontend care pica, build-ul trebuie sa aiba statusul _Failed_, si sa nu se mai creeze bundle-ul.

**Comment by CostescuMarius** [comment]
Am configurat fisierul curent "maven.yml" asftel incat, la fiecare adaugare de cod nou, sa ruleze automat comenzile care instaleaza dependentele si creeaza node-modules (npm install), ruleaza testele de frontend (npm test) si, in cazul in care testele functioneaza, creeaza bundle-ul numit login.js in static/app (npx webpack)
