### ISSUE TITLE
[Frontend] Handle input errors from server for Sign up form

### ISSUE THREAD

**Issue by adrianasbircea** [oxygenxml-incubator/oxygen-account#38]
In [#27](https://github.com/oxygenxml-incubator/oxygen-account/issues/27) si [#35](https://github.com/oxygenxml-incubator/oxygen-account/issues/35) s-a creat un validation service care trimite in raspunsul catre client erorile determinate pentru fiecare field de pe DTO-ul trimis pe request. In modulul de frontend trebuie tratate aceste erori (daca apar) si setata o eroare corespunzatoare pe fiecare input care nu a fost validat de catre server.

**Comment by matrex32** [comment]
Am creat o metoda prin care asignam fiecarui field din front end eroarea de format venita de la server. Am creat un test care sa verifice aceasta functionalitate.
