### ISSUE TITLE
Delete user account

### ISSUE THREAD

**Issue by matrex32** [oxygenxml-incubator/oxygen-account#49]
Trebuie adaugata functionalitatea de stergere prin care userul va putea sa isi stearga contul.
Cand userul va accesa aceasta functionalitate va trebui sa ii apara un pop-up prin intermediul careia userul va fi instiintat ca pentru a efectua actiunea de stergere a contului acesta trebuie sa isi introduca parola.

**Comment by CostescuMarius** [comment]
Closes #50
